; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = esp32dev, nodemcuv2

; ==========================================
; 1. NODO CENTRAL (ESP32 - Sensores)
; ==========================================
[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
upload_port = COM9
monitor_port = COM9
monitor_speed = 115200
build_src_filter = -<*> +<main_esp32.cpp>

lib_deps =
    adafruit/DHT sensor library@^1.4.6
    adafruit/Adafruit Unified Sensor@^1.1.14

; ==========================================
; 2. NODO HMI (NodeMCU ESP8266 - DSKY + InfluxDB)
; ==========================================
[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_port = COM7
monitor_port = COM7
monitor_speed = 115200
build_src_filter = -<*> +<main_nodemcu.cpp>

lib_deps =
    tobiasschuerg/ESP8266 Influxdb@^3.13.0
    marcoschwartz/LiquidCrystal_I2C@^1.1.4
